### ISSUE TITLE
Command Palette: Ctrl-Shift-P: Allow to become bigger if screen is large enough, so user can see more entries

### ISSUE THREAD

**Issue by mherrmann** [fman-community/fman#99]

**Comment by alin23** [comment]
This can be solved with a simple qss rule:

```css
Quicksearch QScrollBar:vertical {
    min-height: 70ex;
}
```
